(() => {
  const data = window.GUIDE_DATA || { pokemon: [], locations: [] };
  const main = document.querySelector('#mainContent');
  const dialog = document.querySelector('#detailDialog');
  const groups = [...data.pokemon.reduce((map, p) => {
    const key = String(p.dexId);
    if (!map.has(key)) map.set(key, []);
    map.get(key).push(p);
    return map;
  }, new Map())].map(([dexId, forms]) => ({ dexId, forms, name: forms[0].name })).sort((a,b) => Number(a.dexId)-Number(b.dexId));
  const formByName = new Map(data.pokemon.map(p => [norm(p.name), p]));
  const store = key => new Set(JSON.parse(localStorage.getItem(key) || '[]').map(String));
  const state = { view: location.hash.slice(1) || 'home', query: '', type: 'all', hideCaught: false, period: 'day', visible: 60, selected: {}, caught: store('radical-red-caught') };
  const esc = value => String(value ?? '').replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  function norm(value){ return String(value || '').toLowerCase().replace(/[éè]/g,'e').replace(/[^a-z0-9]/g,''); }
  function persist(){ localStorage.setItem('radical-red-caught', JSON.stringify([...state.caught])); updateProgress(); }
  function updateProgress(){ const pct=Math.round(state.caught.size/Math.max(groups.length,1)*100); document.querySelector('#headerProgress').textContent=`${pct}%`; }
  function activeForm(group){ return group.forms.find(f=>f.id===state.selected[group.dexId]) || group.forms[0]; }
  function types(p){ return `<div class="types">${p.types.map((t,i)=>`<span style="--type:${p.typeColours[i]}">${esc(t)}</span>`).join('')}</div>`; }
  function navigate(view){ state.view=view; state.visible=60; location.hash=view; document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===view)); render(); scrollTo({top:0,behavior:'smooth'}); }
  function renderHome(){ return `<section class="hero"><div class="hero-copy"><span class="eyebrow">KANTO, REWIRED</span><h1>Plan smarter.<br><em>Catch them all.</em></h1><p>A focused companion for Radical Red's expanded roster and reworked encounters. Your caught Pokémon stay saved on this device.</p><div class="hero-actions"><button class="primary" data-view="pokedex">Open the Pokédex</button><button class="secondary" data-view="locations">Explore locations</button></div></div><div class="hero-orbit"><span></span><b>RR</b></div></section><section class="metrics"><article><strong>${groups.length}</strong><span>Dex entries</span></article><article><strong>${data.pokemon.length}</strong><span>Forms documented</span></article><article><strong>${data.locations.length}</strong><span>Grass & cave locations</span></article><article><strong>${state.caught.size}</strong><span>Caught</span></article></section><div class="section-title"><span class="eyebrow">START HERE</span><h2>Your field kit</h2></div><section class="feature-grid"><button data-view="pokedex"><i>◉</i><b>Complete Pokédex</b><span>Search, filter, inspect stats and mark catches.</span></button><button data-view="locations"><i>☀</i><b>Day & night encounters</b><span>Keep the workbook's paired tables clear and separate.</span></button><button data-view="progress"><i>✓</i><b>Completion tracker</b><span>See exactly how far your current run has come.</span></button></section>`; }
  function filteredGroups(){ const q=norm(state.query); return groups.filter(g=>g.forms.some(p=>(!q || norm(p.name).includes(q) || String(p.dexId).includes(q)) && (state.type==='all'||p.types.includes(state.type))) && (!state.hideCaught||!state.caught.has(g.dexId))); }
  function card(group){ const p=activeForm(group), caught=state.caught.has(group.dexId), idx=group.forms.indexOf(p); return `<article class="poke-card" style="--accent:${p.typeColours[0]||'#d12b42'}"><div class="card-top"><span>#${String(group.dexId).padStart(4,'0')}</span><button class="catch-mini ${caught?'caught':''}" data-caught="${group.dexId}" title="${caught?'Mark not caught':'Mark caught'}">${caught?'✓':'○'}</button></div><button class="poke-open" data-pokemon="${p.id}"><img src="${p.sprite}" alt="${esc(p.name)}"><h3>${esc(p.name)}</h3>${types(p)}<strong>${p.bst} <small>BST</small></strong></button>${group.forms.length>1?`<div class="form-row"><button data-step="-1" data-group="${group.dexId}">‹</button><span>Form ${idx+1} of ${group.forms.length}</span><button data-step="1" data-group="${group.dexId}">›</button></div>`:'<div class="form-row single"><span>Standard form</span></div>'}</article>`; }
  function controls(){ const allTypes=[...new Set(data.pokemon.flatMap(p=>p.types))].sort(); return `<section class="controls"><div class="search-row"><input id="dexSearch" type="search" placeholder="Search by name or number…" value="${esc(state.query)}"><label><input id="hideCaught" type="checkbox" ${state.hideCaught?'checked':''}> Hide caught</label></div><div class="chips"><button class="${state.type==='all'?'active':''}" data-type="all">All</button>${allTypes.map(t=>`<button class="${state.type===t?'active':''}" data-type="${esc(t)}">${esc(t)}</button>`).join('')}</div></section>`; }
  function renderDex(){ const found=filteredGroups(), visible=found.slice(0,state.visible); return `<header class="page-head"><div><span class="eyebrow">RADICAL RED v4.1</span><h1>Pokédex</h1><p>${found.length} entries match · ${state.caught.size} caught</p></div></header>${controls()}<section class="dex-grid">${visible.map(card).join('')||'<p class="empty">No Pokémon match those filters.</p>'}</section>${visible.length<found.length?'<button class="load-more" id="loadMore">Load more</button>':''}`; }
  function encounterCard(e){ const p=formByName.get(norm(e.pokemon)); return `<article class="encounter"><div class="encounter-mon">${p?`<img src="${p.sprite}" alt="">`:''}<div><strong>${esc(e.pokemon)}</strong><span>${e.level?'Lv. '+esc(e.level):'Level varies'}</span></div></div><b>${e.rarity==null?'—':`${e.rarity}%`}</b></article>`; }
  function renderLocations(){ const q=norm(state.query); const places=data.locations.filter(x=>!q||norm(x.name).includes(q)||x[state.period].some(e=>norm(e.pokemon).includes(q))); return `<header class="page-head"><div><span class="eyebrow">ENCOUNTER ATLAS</span><h1>Locations</h1><p>Grass and cave encounters from the v4.1 workbook.</p></div><div class="period-toggle"><button data-period="day" class="${state.period==='day'?'active':''}">☀ Day</button><button data-period="night" class="${state.period==='night'?'active':''}">☾ Night</button></div></header><section class="location-search"><input id="locationSearch" type="search" placeholder="Search a place or Pokémon…" value="${esc(state.query)}"><span>${places.length} locations</span></section><section class="location-grid">${places.map(place=>`<article class="location-panel"><header><div><span>${state.period.toUpperCase()} ENCOUNTERS</span><h2>${esc(place.name)}</h2></div><b>${place[state.period].length} slots</b></header><div>${place[state.period].map(encounterCard).join('')||'<p class="empty small">No encounters listed for this time.</p>'}</div></article>`).join('')}</section>`; }
  function renderProgress(){ const pct=Math.round(state.caught.size/Math.max(groups.length,1)*100); const caught=groups.filter(g=>state.caught.has(g.dexId)); return `<header class="page-head"><div><span class="eyebrow">YOUR JOURNEY</span><h1>Dex progress</h1><p>Stored locally in this browser.</p></div></header><section class="progress-hero"><div class="big-ring" style="--pct:${pct*3.6}deg"><div><strong>${pct}%</strong><span>${state.caught.size} / ${groups.length}</span></div></div><div><span class="eyebrow">CURRENT RUN</span><h2>${state.caught.size?`${state.caught.size} Pokémon secured`:'Your Pokédex is ready'}</h2><p>Open any Pokémon card and use the caught button, or tap the circle directly on a card.</p><button class="primary" data-view="pokedex">Continue catching</button></div></section><section class="caught-list">${caught.slice(-18).reverse().map(g=>{const p=activeForm(g);return `<button data-pokemon="${p.id}"><img src="${p.sprite}" alt=""><span>${esc(g.name)}</span><b>✓</b></button>`}).join('')||'<p class="empty">Caught Pokémon will appear here.</p>'}</section>`; }
  function openPokemon(id){ const p=data.pokemon.find(x=>x.id===Number(id)); if(!p)return; const key=String(p.dexId), caught=state.caught.has(key), labels=['HP','Attack','Defense','Speed','Sp. Atk','Sp. Def']; dialog.querySelector('#dialogContent').innerHTML=`<button class="dialog-close" aria-label="Close">×</button><div class="detail-hero" style="--accent:${p.typeColours[0]}"><img src="${p.sprite}" alt=""><div><span class="eyebrow">#${String(p.dexId).padStart(4,'0')}</span><h2>${esc(p.name)}</h2>${types(p)}<strong>${p.bst} BST</strong></div></div><section class="stats">${p.stats.map((v,i)=>`<div><span>${labels[i]}</span><b>${v}</b><i><em style="width:${Math.min(100,v/1.55)}%"></em></i></div>`).join('')}</section><section class="abilities"><h3>Abilities</h3>${p.abilities.map(a=>`<article><b>${esc(a.name)}</b><p>${esc(a.description||'No description available.')}</p></article>`).join('')}</section><button class="caught-action ${caught?'caught':''}" data-caught="${key}">${caught?'✓ Caught — tap to undo':'Mark as caught'}</button>`; dialog.showModal(); dialog.querySelector('.dialog-close').onclick=()=>dialog.close(); bind(dialog); }
  function bind(root=main){ root.querySelectorAll('[data-view]').forEach(x=>x.onclick=()=>navigate(x.dataset.view)); root.querySelectorAll('[data-caught]').forEach(x=>x.onclick=e=>{e.stopPropagation();const k=x.dataset.caught;state.caught.has(k)?state.caught.delete(k):state.caught.add(k);persist();dialog.open?dialog.close():render(); toast(state.caught.has(k)?'Added to caught Pokémon':'Removed from caught Pokémon');}); root.querySelectorAll('[data-pokemon]').forEach(x=>x.onclick=()=>openPokemon(x.dataset.pokemon)); root.querySelectorAll('[data-step]').forEach(x=>x.onclick=()=>{const g=groups.find(v=>v.dexId===x.dataset.group),p=activeForm(g),next=(g.forms.indexOf(p)+Number(x.dataset.step)+g.forms.length)%g.forms.length;state.selected[g.dexId]=g.forms[next].id;render();}); root.querySelectorAll('[data-type]').forEach(x=>x.onclick=()=>{state.type=x.dataset.type;state.visible=60;render();}); root.querySelectorAll('[data-period]').forEach(x=>x.onclick=()=>{state.period=x.dataset.period;render();}); const ds=root.querySelector('#dexSearch'); if(ds)ds.oninput=e=>{state.query=e.target.value;state.visible=60;render();focusEnd('#dexSearch')}; const ls=root.querySelector('#locationSearch'); if(ls)ls.oninput=e=>{state.query=e.target.value;render();focusEnd('#locationSearch')}; const hc=root.querySelector('#hideCaught'); if(hc)hc.onchange=e=>{state.hideCaught=e.target.checked;render()}; const lm=root.querySelector('#loadMore'); if(lm)lm.onclick=()=>{state.visible+=60;render()}; }
  function focusEnd(sel){requestAnimationFrame(()=>{const x=document.querySelector(sel);x?.focus();x?.setSelectionRange(x.value.length,x.value.length)})}
  function toast(msg){const x=document.querySelector('#toast');x.textContent=msg;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
  function render(){ main.innerHTML=state.view==='pokedex'?renderDex():state.view==='locations'?renderLocations():state.view==='progress'?renderProgress():renderHome(); bind(); updateProgress(); }
  document.querySelectorAll('body>[data-view],.topbar [data-view],.sidebar [data-view],.mobile-nav [data-view]').forEach(x=>x.onclick=()=>navigate(x.dataset.view));
  const global=document.querySelector('#globalSearch'); global.oninput=e=>{state.query=e.target.value; if(state.view==='home'||state.view==='progress')navigate('pokedex');else render();}; document.addEventListener('keydown',e=>{if(e.key==='/'&&!/input/i.test(document.activeElement.tagName)){e.preventDefault();global.focus()}}); dialog.onclick=e=>{if(e.target===dialog)dialog.close()}; render();
})();
